apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      env:
        # Define the environment variable
      - name: PLAYER_INITIAL_LIVES 
        value: 125
      envFrom:
      - configMapRef:
        name: configs
