apiVersion: v1
kind: Pod
metadata:
 name: my-pod
 namespace: roboshop
 labels:
   project: roboshop
   components: frontend
   environment: dev
spec:
 containers:
 - name: nginx
   image: nginx
   ports:
   - containerPort: 80
 - name: busybox
   image: busybox
   command: ["sleep", "3600"]
   
