apiVersion: v1
kind: Pod
metadata: 
  name: resources-pod
  lables:
   type: for-resources-pod
spec:
  containers:
  - name: resources-pod
    image: nginx
    resources:
      requests:
        memory: "68Mi"
        cpu: "100m"
      # assign equal or more than the requests
      limits:
        memory: "100Mi"
        cpu: "120m"
        
